server:
  port: 9000

spring:
  datasource:
    name: postgres
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=kyc}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}

  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:kyc}
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: never

  flyway:
    out-of-order: false
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    schemas: ${DB_SCHEMA:kyc}
    locations:
      - classpath:db/store/{vendor}
      - classpath:db/migration/{vendor}
    baselineOnMigrate: true
    enabled: true
    validateMigrationNaming: true

keri:
  url:  http://localhost:3901 # https://keria.qa.reeve.cf-deployments.org
  booturl: http://localhost:3903 # https://keria-boot.qa.reeve.cf-deployments.org
  identifier:
    bran: 0ADF2TpptgqcDE5IQUF1H
    name: identity
    role: agent
  schema:
    base-url: https://cred-issuance.demo.idw-sandboxes.cf-deployments.org/oobi/
    said: EL9oOWU_7zQn_rD--Xsgi3giCWnFDaNvFMUGTOZx1ARO
  signing-mnemonic: ${KERI_SIGNING_MNEMONIC:test test test test test test test test test test test test test test test test test test test test test test test sauce}

cardano:
  blockfrost:
    url: ${CARDANO_BLOCKFROST_URL:https://cardano-preview.blockfrost.io/api/v0/}
    key: ${CARDANO_BLOCKFROST_KEY:previewh76ch410Jk5ZfMNgWAiVR11yDpmx5vDm}
  issuer:
    pkh:  ${CARDANO_ISSUER_PKH:c8c47610a36034aac6fc58848bdae5c278d994ff502c05455e3b3ee8}   # 28-byte payment key hash hex (56 chars)
    vkey: ${CARDANO_ISSUER_VKEY:6ea31d27d585439ea8fd9cd8e6664ed83e605c06aec24d32dfaba488e49287d9}  # 32-byte raw Ed25519 public key hex (64 chars) — required for TEL datum
  network: preview

apiPrefix: ${API_PREFIX:/yaci-api}
store:
  cardano:
    host: ${STORE_CARDANO_HOST:preview-node.play.dev.cardano.org}
    port: ${STORE_CARDANO_PORT:3001}
    protocol-magic: 2
    sync-start-slot: 107155208
    sync-start-blockhash: 0031e5d9e37a9077e9b5e2b234b438ad6bb2e14528011d6c4e31c167741e5ae6
#    protocol-magic: 42
#    # for devnet we must specify the genesis files for Yaci-Store
#    byron-genesis-file: classpath:/devkit/byron-genesis.json
#    shelley-genesis-file: classpath:/devkit/shelley-genesis.json
#    alonzo-genesis-file: classpath:/devkit/alonzo-genesis.json
#    conway-genesis-file: classpath:/devkit/conway-genesis.json
  executor:
    enable-parallel-processing: false
  core:
    enabled: true
  metadata:
    api-enabled: false