name = "cardanofoundation/kyc-whitelist"
version = "0.1.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "KYC Whitelisting smart contracts for Cardano stablecoins"

[repository]
user = "cardanofoundation"
project = "kyc-whitelist"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config]
